### ISSUE TITLE
Reading data from functions

### ISSUE THREAD

**Issue by Stasik0** [acplt/open62541#114]
Sup!

there is one issue I have discussed with @jpfr and I think @uleon raised it already a couple of months ago. The question is: how can we read data not only from data pointers but also from callback functions?

The probably most simple and brutal solution is to modify UA_Variant
```c
typedef struct UA_Variant {
	UA_VTable_Entry *vt;          // internal entry into vTable
	UA_Int32  arrayLength;        // total number of elements
	void     *data;
	UA_Int32  arrayDimensionsLength;
	UA_Int32 *arrayDimensions;
} UA_Variant;
```

into something like
```c
typedef struct UA_AccessFuntions {
	(void*)(*readValue)();
	(void)(*writeValue)(void*);
} UA_AccessFuntions;
union data_function
{
  void     *data
  struct   UA_AccessFuntions AccessFuntions;
};
enum UA_VARIANT_TYPEenum {
	UA_VARIANT_TYPE_data           = 0x01,
	UA_VARIANT_TYPE_funcitons       = 0x02
};
typedef struct UA_Variant {
	UA_VTable_Entry *vt;          // internal entry into vTable
	UA_Int32  arrayLength;        // total number of elements
	UA_Byte variantType;
	union data_function dataFunction:
	UA_Int32  arrayDimensionsLength;
	UA_Int32 *arrayDimensions;
} UA_Variant;
```

so we have a possibility to store a data pointer or pointers to the access functions in the variant, this approach (for reading) only needs the adoption the encoding functions for variant (that are already custom). Writing will need some adoption of write services.

We will probably need some arguments to the functions (e.g. node id), however for the first needs it may be fufficient. Is everyone okay with this?

**Comment by jpfr** [comment]
@Stasik0 
This feature just landed in the typedescription branch.
https://github.com/acplt/open62541/blob/typedescription/examples/opcuaServerDataSource.c

This is the essential part for adding a node that always returns the current time.
```c
static UA_StatusCode readTimeData(const void *handle, UA_VariantData* data) {
    UA_DateTime *time = UA_DateTime_new();
    if(!time)
        return UA_STATUSCODE_BADOUTOFMEMORY;
    *time = UA_DateTime_now();
    data->arrayLength = 1;
    data->dataPtr = time;
    data->arrayDimensionsSize = -1;
    data->arrayDimensions = UA_NULL;
    return UA_STATUSCODE_GOOD;
}

static void releaseTimeData(const void *handle, UA_VariantData* data) {
    UA_DateTime_delete((UA_DateTime*)data->dataPtr);
}

static void destroyTimeDataSource(const void *handle) {
    return;
}

// add node with a callback to the userspace
UA_Variant *myDateTimeVariant = UA_Variant_new();
myDateTimeVariant->storageType = UA_VARIANT_DATASOURCE;
myDateTimeVariant->storage.datasource = (UA_VariantDataSource)
    {.handle = UA_NULL, .read = readTimeData, .release = releaseTimeData,
     .write = (UA_StatusCode (*)(const void*, const UA_VariantData*))UA_NULL,
     .destroy = destroyTimeDataSource};
myDateTimeVariant->type = &UA_TYPES[UA_TYPES_DATETIME];
myDateTimeVariant->typeId = UA_NODEID_STATIC(UA_TYPES_IDS[UA_TYPES_DATETIME],0);

UA_QualifiedName myDateTimeName;
UA_QUALIFIEDNAME_ASSIGN(myDateTimeName, "the time");
UA_Server_addVariableNode(server, myDateTimeVariant, &UA_NODEID_NULL, &myDateTimeName,
                          &UA_NODEID_STATIC(UA_NS0ID_OBJECTSFOLDER,0),
                          &UA_NODEID_STATIC(UA_NS0ID_ORGANIZES,0));

```

**Comment by Stasik0** [comment]
:top:

**Comment by Stasik0** [comment]
okay @jpfr, very nice,

2 issues: 
* why is UDP gone? 
* I tried to modify the normal server (with the memshared variable), to increase 42 in the callback, however the value does not change (i think it is probably copied somewhere) could you please look into it?

**Comment by jpfr** [comment]
1. Is it ok if we move udp into a separate ```examples/server_udp.c``` with a minimal working example? We could have ```examples/server_datasource.c```, etc. separately for people looking up a specific feature.

2. VariableNodes are immutable. So when a variable is overwritten, we replace the entire thing. So yes, variables are "moved" in memory for updates.
If you want to map a specific memory location to a variable, use the datasource mechanism. But then you need locking to protect against parallel reads/writes. The ```.release``` function in the datasource is called when a read is finished.

**Comment by jpfr** [comment]
Ok. We now support writing into data source via the write-service. (1a54a765a6d2020a02d58c1d7fa4bc8a58c7a032)

https://github.com/acplt/open62541/blob/typedescription/examples/server_datasource.c#L47
In the example, a callback prints the value of a global variable to stdout. And we can change it via the UA service.

**Comment by jpfr** [comment]
Solved on master.
See ```/examples/server_datasource.c```.
