### ISSUE TITLE
Move main-loop into the server (from the networklayer)

### ISSUE THREAD

**Issue by jpfr** [acplt/open62541#136]
Hey all,

Currently, the network layer contains an "infinite" loop that runs ```select``` with a timeout.
Thinking forward, we could have this "main-loop" in the server. This way, we can
- Have multiple networklayers (all binary/xml/mixed)
- Run subscription-handling and internal cleanup functions with different timeouts and frequencies than the networklayer
- Include callbacks to user-supplied background functions in a single-threaded environment without messing with the network layer.

And it could work for the multithreaded (with a threadpool) and single-threaded case without changing the API of the network layer.

**Mockup-Code**
```c
// server initialisation
UA_Server *server = UA_Server_new();
NetworkLayer *nl1 = myNetworkLayerImplementation(device, port);
NetworkLayer *nl2 = myNetworkLayerImplementation(device2, port);
Server_addNetworkLayer(server, nl1);
Server_addNetworkLayer(server, nl2);
Server_registerPeriodicCallback(server, cllbck, timout); // user-defined callback
Server_run(server);
...

// inside Server_run
while(true) {
    for(int i=0;i<networkLayersSize;i++)
        networkLayers[i].worker(networkLayers[i].handle, server); // select (timeout zero)
    Server_answerSubscriptions(server);
    Server_runRegisteredCallbacks(server);
    if(timeout)
        Server_housekeeping(server);
    sleep(...); // some policy to tradeoff burned cpu cycles and reactiveness
}
```

Ideas, suggestions, critique?

**Comment by Stasik0** [comment]
https://github.com/acplt/open62541/blob/734016e9f21363e256f777fdeef672b05fedf92f/src/server/ua_server_worker.c#L406

probably can be closed?
