### ISSUE TITLE
Server configuration API

### ISSUE THREAD

**Issue by jpfr** [acplt/open62541#151]
Currently, users who want to set another application URI, etc. need to touch the code of the library itself. It can't be configured in "userspace".

We should expose the couple configuration options as UA_Server_xxx(...) functions.

```c
typedef struct {
	UA_String applicationUri;
	UA_String productUri;
	UA_LocalizedText applicationName;
	UA_ApplicationType applicationType;
	UA_String gatewayServerUri;
	UA_String discoveryProfileUri;
	UA_Int32 discoveryUrlsSize;
	UA_String* discoveryUrls;
} UA_ApplicationDescription;
```
Currently, we work around having discoveryUrls by mirorring the client the URL back under which he tried to reach us in the getendpointsdescription service.

Any ideas or wishes for this?
Once we have proper configuration from userland, what do we need additionally for a "proper" first release?

**Comment by Stasik0** [comment]
user/passwords list

**Comment by jpfr** [comment]
closing the issue. we instantiate the server with a configuration.
online reconfiguration will get added on an as-needed basis.
