### ISSUE TITLE
steps towards mingw cross-compiling

### ISSUE THREAD

**Issue by Stasik0** [acplt/open62541#159]
hi gang,

i have started to look into cross-compiling windows binaries on the linux machine

@jpfr could you please examine my changes?

cross compiling can be done on ubuntu as follows:

```
sudo apt-get install gcc-mingw-w64-i686
cmake -DCMAKE_TOOLCHAIN_FILE=Toolchain-mingw32.cmake .
make
```

the dll compiles, however i have problems compiling networklayer_tcp

```
[ 83%] Building C object CMakeFiles/exampleServer.dir/examples/networklayer_tcp.c.obj
/home/sten/Desktop/open62541/examples/networklayer_tcp.c: In function ‘writeCallback’:
/home/sten/Desktop/open62541/examples/networklayer_tcp.c:209:14: error: pointer targets in assignment differ in signedness [-Werror=pointer-sign]
   buf[i].buf = gather_buf.strings[i].data;
              ^
/home/sten/Desktop/open62541/examples/networklayer_tcp.c: In function ‘NetworkLayerTCP_start’:
/home/sten/Desktop/open62541/examples/networklayer_tcp.c:249:60: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
  if((layer->serversockfd = socket(PF_INET, SOCK_STREAM,0)) == INVALID_SOCKET) {
                                                            ^
cc1: all warnings being treated as errors
make[2]: *** [CMakeFiles/exampleServer.dir/examples/networklayer_tcp.c.obj] Error 1
make[1]: *** [CMakeFiles/exampleServer.dir/all] Error 2
make: *** [all] Error 2
```

can any of our socket gurus help me?

**Comment by jpfr** [comment]
Hey Sten,
can you post your Toolchain-mingw32.cmake?

**Comment by jpfr** [comment]
On my box, I had to do the following change:
```
-set(CMAKE_C_COMPILER /opt/mingw/usr/bin/i686-pc-mingw32-gcc)
-set(CMAKE_CXX_COMPILER /opt/mingw/usr/bin/i686-pc-mingw32-g++)
-set(CMAKE_RC_COMPILER /opt/mingw/usr/bin/i686-pc-mingw32-windres)
-set(CMAKE_FIND_ROOT_PATH /opt/mingw/usr/i686-pc-mingw32)
+set(CMAKE_C_COMPILER i686-w64-mingw32-gcc)
+set(CMAKE_CXX_COMPILER i686-w64-mingw32-g++)
+set(CMAKE_RC_COMPILER i686-w64-mingw32-windres)
+set(CMAKE_FIND_ROOT_PATH i686-w64-mingw32)
```

**Comment by Stasik0** [comment]
okay, i got cross compiling working on travis, had to workeround a number of weird bugs, its seems to be a combunation of windows headers and gcc 4.6

redefinitions e.g. in queue.h
https://travis-ci.org/acplt/open62541/builds/47111760#L307
or for "writeWalue" 
https://travis-ci.org/acplt/open62541/builds/47113343#L320
and some signness
https://travis-ci.org/acplt/open62541/builds/47113733#L334
https://travis-ci.org/acplt/open62541/builds/47114421#L334

the caviat is that is compiles now, however networklayer_udp is still broken, could someone make it compile please?
https://github.com/acplt/open62541/blob/master/examples/networklayer_udp.c#L110
