### ISSUE TITLE
Recurrent Clean-Up in the Server

### ISSUE THREAD

**Issue by jpfr** [acplt/open62541#162]
We now have the infrastructure for *timed* and *repeated* work in the server.
When the timer runs out, the work (a function call with some pointer to data) is executed.

Currently we do kick out users whose securechannel or session has timed out.
How about we add one function that is repeated every n seconds that handles all internal cleanups of that sort?

@FlorianPalm You built the *managers* for securechannels and sessions. Is the clean-up as easy as iterating over the linked lists in the managers? What if we add more "state" to the sessions, such as subscriptions?

**Comment by FlorianPalm** [comment]
This function could also update the session array in ns0.
In my oppinion yes it is. Subscritption would be cool. This would lead to another managing component within the server which allows clients to subcript variables/nodes, checks time to live of subscriptions etc.

**Comment by Stasik0** [comment]
we need to cleanup stale securechannels and sessions at first

**Comment by jpfr** [comment]
done.
There is a function UA_Server_cleanup that is called every 10 seconds.
