### ISSUE TITLE
Did anyone tested writing values?

### ISSUE THREAD

**Issue by IronCaterpillar** [acplt/open62541#163]
I had a very strange problems during my tries to write values of exampleServer. At first attempt to write "the answer" value I've got a "BadWriteNotSupported" error. I've digget into debugger and understood, that somehow this code:
*switch(aWriteValue->attributeId) {
        case UA_ATTRIBUTEID_NODEID:
            /* if(aWriteValue->value.encodingMask == UA_DATAVALUE_ENCODINGMASK_VARIANT){ } */
            retval = UA_STATUSCODE_BADWRITENOTSUPPORTED;
            break;* 
in ua_services_attribute.c works wrong(it's not understandable for me, how the variable, that have a value of 13 can get into the case UA_ATTRIBUTEID_NODEID, that have a value of 1). Then I removed this case to see what will happen further. Then I' ve stopped on the string:
*case UA_ATTRIBUTEID_VALUE:
            if(newNode->nodeClass != ((UA_NODECLASS_VARIABLE) | UA_NODECLASS_VARIABLETYPE)) {
                retval = UA_STATUSCODE_BADWRITENOTSUPPORTED;
                break;
            }* 
and changed it to 
*case UA_ATTRIBUTEID_VALUE:
            if(newNode->nodeClass != (UA_NODECLASS_VARIABLE)&& newNode->nodeClass !=(UA_NODECLASS_VARIABLETYPE)) {
                retval = UA_STATUSCODE_BADWRITENOTSUPPORTED;
                break;
            }*
Now it works, but I'm sure, that it is a wrong way of fixing this issue.

**Comment by FlorianPalm** [comment]
Yes, you are right!
