### ISSUE TITLE
distribute queue.h instead of downloading?

### ISSUE THREAD

**Issue by Stasik0** [acplt/open62541#167]
Can we distribute queue.h in the ```include/ext/``` directory instead of downloading it? Then we can add fixes from master (something winnt related) into it. Any objections? What is with the license?

**Comment by jpfr** [comment]
done in the typedescription branch

**Comment by Stasik0** [comment]
@jpfr nope :( redefinition stuff again https://travis-ci.org/acplt/open62541/builds/51961487#L362

**Comment by jpfr** [comment]
dang!

travis is really teaching patience.
this did it: 43f9f6cf6c01bfa026ec08fa53767c46a112092c

**Comment by Stasik0** [comment]
1 more questuon: we had a problem that queue on linux was broken (some older kernel), why not always including our queue.h?
