### ISSUE TITLE
Client API

### ISSUE THREAD

**Issue by jpfr** [acplt/open62541#179]
Hey there,

there's a client API in the works:
https://github.com/acplt/open62541/blob/client/include/ua_client.h
https://github.com/acplt/open62541/blob/client/src/client/ua_client.c

a) How do you want the API to look like?
b) Who is going to developt it?
Currently it's basically 1:1 from @FlorianPalm's example client. Now we can expose more and more UA services to the user.

**Comment by Stasik0** [comment]
ua_client.h und ud_client.c are merged into master
