### ISSUE TITLE
Crash exampleClient in Windows

### ISSUE THREAD

**Issue by kadomcev** [acplt/open62541#187]

**Comment by kadomcev** [comment]
$ exampleClient.exe
1st parameter: number of nodes to read
2nd parameter: number of read-tries
3rd parameter: name of the file to save measurement data
4th parameter: 1 = read same node, 0 = read different nodes
5th parameter: ip adress
6th parameter: port
7th parameter: 0=stateful, 1=stateless
8th parameter: 0=tcp, 1=udp (only with stateless calls)

Using default parameters.
sock = 1884
sock = 1872
mean time for handling request:     7.5000000000 ms
received: 66

**Comment by kadomcev** [comment]
crash occurs when the code:
	//save to file
	char data[100];
	const char flag = 'a';
	FILE* fHandle = UA_NULL;
	if (defaultParams) {
		fHandle =  fopen("client.log", &flag);
	}else{
		fHandle =  fopen(argv[3], &flag);
	}
	//header

	UA_Int32 bytesToWrite = sprintf(data, "measurement %s in ms, nodesToRead %d \n", argv[3], nodesToReadSize);
	fwrite(data,1,bytesToWrite,fHandle);
	for(UA_UInt32 i=0;i<tries;i++) {
		bytesToWrite = sprintf(data,"%16.10f \n",timeDiffs[i]);
		fwrite(data,1,bytesToWrite,fHandle);
	}
	fclose(fHandle);

**Comment by kadomcev** [comment]
problem solved

**Comment by FlorianPalm** [comment]
What was the problem?

**Comment by kadomcev** [comment]
no problem)
