### ISSUE TITLE
UaExpert > Attribute of node > DataType > not set

### ISSUE THREAD

**Issue by kadomcev** [acplt/open62541#191]
/* Add Folder ADE7878 - TYPE:String */
UA_ObjectNode *root = UA_ObjectNode_new();
UA_QUALIFIEDNAME_STATIC(root->browseName, "ADE7878");
UA_LOCALIZEDTEXT_STATIC(root->displayName, "ADE7878");
UA_LOCALIZEDTEXT_STATIC(root->description, "ADE7878");

root->nodeClass = UA_NODECLASS_OBJECT;
root->nodeId.namespaceIndex = 0;
root->nodeId.identifierType = UA_NODEIDTYPE_STRING;
root->eventNotifier = UA_FALSE;
UA_String_copycstring("ADE7878", &root->nodeId.identifier.string);
res = UA_Server_addNode(server, (UA_Node*)root,
							&UA_EXPANDEDNODEID_STATIC(0, UA_NS0ID_OBJECTSFOLDER),
							&UA_NODEID_STATIC(0, UA_NS0ID_ORGANIZES));
							//&UA_NODEID_STATIC(0, UA_NS0ID_FOLDERTYPE));
ADE7878 = res.addedNodeId;
printf("statusCode = %08X\n",res.statusCode);
ADDREFERENCE(ADE7878, UA_NODEID_STATIC(0, UA_NS0ID_HASTYPEDEFINITION),
				 UA_EXPANDEDNODEID_STATIC(0, UA_NS0ID_FOLDERTYPE));

/********************************************************************************************/
/* Add node 'Ua' in folder ADE7878 - TYPE:String */
UA_ExpandedNodeId parentNode;
parentNode.nodeId = ADE7878;
UA_VariableNode *rootNode = UA_VariableNode_new();
UA_QUALIFIEDNAME_STATIC(rootNode->browseName, "Ua");
UA_LOCALIZEDTEXT_STATIC(rootNode->displayName, "Ua");
UA_LOCALIZEDTEXT_STATIC(rootNode->description, "Ua");

rootNode->nodeClass = UA_NODECLASS_VARIABLE;
rootNode->nodeId.namespaceIndex = 0;
rootNode->nodeId.identifierType = UA_NODEIDTYPE_STRING;
UA_String_copycstring("ADE7878.Ua", &rootNode->nodeId.identifier.string);

rootNode->value.type = &UA_TYPES[UA_TYPES_INT32];
rootNode->value.storage.data.dataPtr = myInteger;
rootNode->value.storageType = UA_VARIANT_DATA_NODELETE;
rootNode->value.storage.data.arrayLength = 1;
res = UA_Server_addNode(server, (UA_Node*)rootNode,
							&parentNode,
							&UA_NODEID_STATIC(0, UA_NS0ID_HASCOMPONENT));
printf("statusCode = %08X\n",res.statusCode);

**Comment by kadomcev** [comment]
![1](https://cloud.githubusercontent.com/assets/11058275/6419872/3ebf02c4-beeb-11e4-86be-9a4c00aa68dc.png)

**Comment by jpfr** [comment]
Look at how the variant type is defined.
https://github.com/acplt/open62541/blob/master/include/ua_types.h#L220

You do not set the typeId in your current code.
Just use this function to set the value of the variant: ```UA_Variant_setValue(UA_Variant *v, void *p, UA_UInt16 typeIndex);```

**Comment by kadomcev** [comment]
/* Add node 'Ua' in folder ADE7878 - TYPE:String */
UA_ExpandedNodeId parentNode;
parentNode.nodeId = ADE7878;
UA_VariableNode *rootNode = UA_VariableNode_new();
UA_QUALIFIEDNAME_STATIC(rootNode->browseName, "Ua");
UA_LOCALIZEDTEXT_STATIC(rootNode->displayName, "Ua");
UA_LOCALIZEDTEXT_STATIC(rootNode->description, "Ua");

rootNode->nodeClass = UA_NODECLASS_VARIABLE;
rootNode->nodeId.namespaceIndex = 0;
rootNode->nodeId.identifierType = UA_NODEIDTYPE_STRING;
UA_String_copycstring("ADE7878.Ua", &rootNode->nodeId.identifier.string);

UA_Variant_setValue(&rootNode->value, myInteger, UA_TYPES_INT32);
//rootNode->value.type = &UA_TYPES[UA_TYPES_INT32];
//rootNode->value.storage.data.dataPtr = myInteger;
rootNode->value.storageType = UA_VARIANT_DATA_NODELETE;
rootNode->value.storage.data.arrayLength = 1;
res = UA_Server_addNode(server, (UA_Node*)rootNode,
							&parentNode,
							&UA_NODEID_STATIC(0, UA_NS0ID_HASCOMPONENT));
printf("statusCode = %08X\n",res.statusCode);

changed only identifier

**Comment by kadomcev** [comment]
![2](https://cloud.githubusercontent.com/assets/11058275/6420568/7506e846-bef1-11e4-9a08-646b5e5f84f4.png)

**Comment by jpfr** [comment]
Looks god. NodeId(ns=0, i=6) stands for UA_Int32.
Can we close this?

**Comment by kadomcev** [comment]
![3](https://cloud.githubusercontent.com/assets/11058275/6424703/0c5c7328-bf2e-11e4-82b6-87d81fa9f696.png)

**Comment by kadomcev** [comment]
UaCPPServer > Attribute of node > DataType > Byte is set

**Comment by Stasik0** [comment]
I stared into wireshark just for an hour, and i can not find any difference :( on the wire it looks the same (at least for me), anyone else any idea?

**Comment by Stasik0** [comment]
please confirm the fix @kadomcev

**Comment by kadomcev** [comment]
I confirm, all fine
![5](https://cloud.githubusercontent.com/assets/11058275/6430405/0ab75776-c033-11e4-91d1-5154d2b8b273.png)
However, in the Data Access View - >DataType -> NULL
![6](https://cloud.githubusercontent.com/assets/11058275/6430472/6f683580-c035-11e4-8f1d-336e7076a439.png)

**Comment by Stasik0** [comment]
And also no value, correct? :(

**Comment by kadomcev** [comment]
yes:(

**Comment by Stasik0** [comment]
Could you make a new bug and close this one, please? With the screenshot?

**Comment by kadomcev** [comment]
ok
