### ISSUE TITLE
Problem client with ReadResponse

### ISSUE THREAD

**Issue by kadomcev** [acplt/open62541#192]
Client-open62541 http://s000.tinyupload.com/?file_id=01966971779198977548
UaExpert http://s000.tinyupload.com/?file_id=64529914956081845468

**Comment by Stasik0** [comment]
Did not get it :/ could you state it more precisely?

**Comment by kadomcev** [comment]
I try get value of node, but received null value

**Comment by kadomcev** [comment]
In request  you can see which nodes i need read
