### ISSUE TITLE
Problem with Data Access View - >DataType -> NULL

### ISSUE THREAD

**Issue by kadomcev** [acplt/open62541#193]
Hi all.
Data Access View - >DataType -> NULL
Data Access View - >Value -> not set

![5](https://cloud.githubusercontent.com/assets/11058275/6430589/d561450c-c03a-11e4-8c23-34dce397e1f8.png)
![6](https://cloud.githubusercontent.com/assets/11058275/6430590/dc48ebd6-c03a-11e4-8328-364ba7b8a024.png)

**Comment by Stasik0** [comment]
it is because of the missing CreateSubsription service

**Comment by kadomcev** [comment]
ok
