### ISSUE TITLE
Q: how to work with functions...

### ISSUE THREAD

**Issue by kadomcev** [acplt/open62541#194]
Service_CreateSubscription
Service_Publish
Service_SetPublishingMode

**Comment by FlorianPalm** [comment]
Please provide further information what your concern is. Perhaps this issue or the solution of it could be useful to anyone else. At the momen I am not sure what your question/problem is. These services are not implemented at the moment.

**Comment by kadomcev** [comment]
These services does not work?

**Comment by Stasik0** [comment]
they are not yet implemented
