### ISSUE TITLE
Problem with the output tree

### ISSUE THREAD

**Issue by kadomcev** [acplt/open62541#202]
Hi all.
![7](https://cloud.githubusercontent.com/assets/11058275/6542974/e9f105e0-c533-11e4-8d25-0ffeabb32115.png)
This occurs at the program level or server level?
What is the problem?

**Comment by Stasik0** [comment]
what is the problem?

**Comment by kadomcev** [comment]
numbering is not in order

**Comment by kadomcev** [comment]
1, 10, 11 etc

**Comment by Stasik0** [comment]
considered as strngs they are sorted in right order... open wieshark and look the BrowseResponse of the server... if results are reordered - it is UaExpert's problem...

**Comment by Stasik0** [comment]
solved?

**Comment by kadomcev** [comment]
can you check out?

**Comment by kadomcev** [comment]
I'll implement subscription's

**Comment by Stasik0** [comment]
i probably will no check :) i am pretty sure they are sorted as strings
