### ISSUE TITLE
UA_MULTITHREADING

### ISSUE THREAD

**Issue by kadomcev** [acplt/open62541#205]
Hi all.
How can i build project with UA_MULTITHREADING ?

**Comment by Stasik0** [comment]
cmake -DUA_MULTITHREADING=on

**Comment by kadomcev** [comment]
for Windows ??? urcu not found

**Comment by jpfr** [comment]
Hello @kadomcev,

we use liburcu (http://urcu.so/) for multithreading that scales to many cpu cores (32+).
Liburcu is not available for windows so far (porting is possible though).

If you have a concrete use case, where
- Windows is used
- open62541 without multithreading is the bottleneck of you application
- you have measuruments showing that open62541 is the bottleneck

then I'll gladly port multithreading to windows. Until then, this is **wontfix**.
