### ISSUE TITLE
Remove the "open62541" namespace and application name

### ISSUE THREAD

**Issue by jpfr** [acplt/open62541#218]
Currently, there is no way to add namespaces and to change the standard application name from outside the library.

Both should be provided for in the 0.1 release.

**Comment by Stasik0** [comment]
do you mean this branch?
https://github.com/acplt/open62541/blob/f1ce7710ac3e997e96fc621622c5af326330d026/src/server/ua_server.c#L102

**Comment by Stasik0** [comment]
relates to #151, is this a duplicate?

**Comment by Stasik0** [comment]
is now set via server config: https://github.com/acplt/open62541/blob/master/src/server/ua_server.c#L18
still hardcoded for certificate generation, we need to doc it somewhere
