### ISSUE TITLE
 error: to be safe all intermediate pointers in cast from * must be 'const' qualified

### ISSUE THREAD

**Issue by nwmcsween** [acplt/open62541#228]
see here for stderr output: http://sprunge.us/PQSj seems open62541 isn't working with urcu properly.

**Comment by Stasik0** [comment]
do you mean the multi-threaded version? We compile it automatically https://travis-ci.org/acplt/open62541#L696, check the liburcu version, we use 0.8.5 at the moment,

**Comment by nwmcsween** [comment]
I tried with got ucru

**Comment by nwmcsween** [comment]
I tried with git  ucru

**Comment by Stasik0** [comment]
just try the 0.8.5 tag http://git.lttng.org/?p=userspace-rcu.git;a=commit;h=56594c3ae8d298709e99795e477df076bb11bc6d
