### ISSUE TITLE
ua_types.h - wtf?

### ISSUE THREAD

**Issue by nwmcsween** [acplt/open62541#230]
why in gods name do you typedef already typedefed types by the c library?

**Comment by Stasik0** [comment]
do you mean something like this? ```typedef int64_t UA_Int64;```

**Comment by nwmcsween** [comment]
Yes it is uneeded as the libc types the primitive types

**Comment by Stasik0** [comment]
the reason is that we want to be close to the IEC 62541 standard. There a "UInt32" type is defined and not a "uint32_t".

**Comment by ichrispa** [comment]
I perfectly agree that using the standard compliant naming scheme is essential. Lots of the code gets generated by using the standard as a reference. Node values in the namespace generator script for example only need to `print "UA_"+self.getStringName` to create a new UA_Int32, UA_String, UA_Byte, etc.. The script was written completely independantly of open62541 an thanks to the standard compliant naming scheme, this sort of stuff works ^^
