### ISSUE TITLE
How much of NS0 should we implement?

### ISSUE THREAD

**Issue by Stasik0** [acplt/open62541#233]
At the moment we have a minor subset of NS0 implemented. There is obvious a trade-off between the size of the binary and the included NS0-Subset.

As example there are sub-nodes of ServerCapabilits and ServerDiagnostics missing that are marked as mandatory in the standard.

What is our strategy? Just being pragmatic to ensure client interoperation (relates to #232) ant tests? Or to cover all mandatory nodes explicitly?

**Comment by Stasik0** [comment]
From the UaExpert forum, I have got a following suggestion. Apparently it should work with most clients.

![addressspace](https://cloud.githubusercontent.com/assets/469170/7352678/d81707e6-ed0d-11e4-86d3-b7f9ff17eee8.png)

should we stick on this?

**Comment by jpfr** [comment]
:+1:
