### ISSUE TITLE
Library code in C++/C#

### ISSUE THREAD

**Issue by davy7125** [acplt/open62541#234]
Hi,

I tried to use the dll provided in a C# project. I was stuck on an AccessViolationError in the method UA_Client_connect but it may be related to problems with managed / unmanaged code. So finally I'll make a C++ project using the library.

Anyway, here are some changes to do in the example code and in the .h, if someone else try to use the library instead of the .h / .c:

UA_Client *client = UA_Client_new(UA_ClientConfig_standard);
 ==> UA_Client_new has a logger as a second argument
 ==> UA_ClientConfig_standard is not exported with UA_EXPORT and cannot be used (Logger_Stdout_new is also not exported)

UA_StatusCode retval = UA_Client_connect(client, ClientNetworkLayerTCP_connect,
                                             "opc.tcp://localhost:16664");
 ==> ClientNetworkLayerTCP_connect is not exported either

req.nodesToRead = UA_ReadValueId_new();
 ==> a cast "(UA_ReadValueId*)" is missing (some compiler won't accept this)

req.nodesToRead[0].nodeId = UA_NODEID_STRING(1, "the.answer");
 ==> please use macro only inside the library. It triggers errors with C++ compilers and it's not exportable. Wrap the different versions in a function (which has to be exported with UA_EXPORT as well) for a better compatibility.

Regards,
Davy

**Comment by Stasik0** [comment]
hi Davy,

the problems you have are with the c++ compiler right?

Best Regards,
Sten

**Comment by davy7125** [comment]
There is no problem building the library using a C++ compiler (I tried Visual C++ 2010 & 2013).

What I pointed out is the fact that the dll doesn't comprise some functions present in the example code. To fix this, some UA_EXPORT must be added and some macros should be wrapped within exported functions (UA_NODEID_STRING for instance). By doing so, the dll could be easily used with dll imports in other projects.

Davy

**Comment by Stasik0** [comment]
okay, now i understand we do not notice the problem since we do not link the client with the dll in our test builds...

**Comment by Stasik0** [comment]
@davy7125 okay, the structs and functions are exposed now, I have added a dynamic linking to the standard test build - we will not miss such an error later
Wrapping macros is still open

**Comment by davy7125** [comment]
Thanks a lot!

Regarding the macros, I quickly drafted something like this:

(in .h, important)
UA_NodeId UA_EXPORT GetNodeId(UA_UInt16 namespaceIndex, const char * identifier);

(in .c, you are free)
UA_NodeId GetNodeId(UA_UInt16 namespaceIndex, const char * identifier)
{
	UA_NodeId nodeIdRet;
	nodeIdRet.namespaceIndex = namespaceIndex;
	nodeIdRet.identifierType = UA_NODEIDTYPE_STRING;
	nodeIdRet.identifier.string = UA_STRING(identifier);
	return nodeIdRet;
}

**Comment by jpfr** [comment]
Hello Davy,
the changes you proposed have landed in cf33d08b7df06b9a6b57e33bdb03c85e2503ea8d.

**Comment by Stasik0** [comment]
@davy7125 is it okay to close?

**Comment by davy7125** [comment]
I don't have my computer right now but from what I saw in the commits that sounds good!

**Comment by Stasik0** [comment]
@davy7125 okay :) are you interesting in publishing your C# biding together with open62541 when you are done?

**Comment by davy7125** [comment]
It didn't work in binding the library directly in a C# project. I had an access memory violation when the library called a method from WinSock.
What I can provide is the class I implemented with C++ / CLI (C++ with a mix of managed / unmanaged for the .NET framework). Here is a link that can describe the process:
http://www.codeproject.com/Articles/651516/Exposing-native-to-managed-Cplusplus-CLI-vs-P-Invo
But I'm still with the RC3 version of the library. What is the tool providing a single .h and .c from the sources?

Regards,
Davy

**Comment by Stasik0** [comment]
to obtain single source files you basically need to checkout and to run
`cmake -DENABLE_AMALGAMATION=ON .`

**Comment by Stasik0** [comment]
@davy7125 i have just tagged an RC4, you can use the files from it

**Comment by davy7125** [comment]
Thank you for your work. I used the .h and .c provided and everything is fine.

Here are the steps to use open62541 with a C# .NET project (I may open a new thread in the forum, or I let you copy / paste these information somewhere else).

# Building open62541 with visual studio

First, I compiled open62541.h and open62541.cpp using Visual C++ 2013, which is compatible with C99. The project I created is a C++ project, excluding the Common Language Runtime Support (no managed code). I linked the project against winsock, which is w2_32.lib on Windows 7.
When the build is done, open62541.dll and open62541.lib are created.

# Creating a C++ / CLI project

Then I created a C++/CLI dll project. I added the .h you provided and linked against open62541.lib previously built. open62541.dll is in the project directory.

Note: for compatibility reason with my other projects I had to use Visual Studio 2010 and C99 is not enabled. I had to change these lines in open62541.h
#include <stdint.h>     =>   #include "stdint.h"
#include <stdbool.h>    =>   #include "stdbool.h"
I manually added the two files "stdint.h" and "stdbool.h" in the project.

I then created classes to interface with the library. Please note that it's in an early stage of the development and that only basic features are provided. I'm using log4net as logger.


## LibOpen62541.h

```C++
#pragma once

#include "Logger.h"
#include <string>
using namespace System;
using namespace log4net;

// Stands as a forward declaration for the opaque struct UA_Client,
// and a hack to get rid of the LNK4248 warnings
struct UA_Client {};

// Managed class (keyword 'ref')
public ref class LibOpen62541
{
public:
  LibOpen62541();
  ~LibOpen62541() { this->!LibOpen62541(); } // The destructor calls the finalizer
  !LibOpen62541(); // Disconnect and free unmanaged resources
  
  // Try to connect to an address (if the connection is not already done)
  // Return true if connected
  bool Connect(String^ hostAddress);

  // Retrieve a value
  // Works with bool, byte, char, (U)Int16/32/64, float, double, String^
  template<typename T> T Get(String^ parameter);
  template<> String^ Get<String^>(String^ parameter);

private:
  template<typename T> int GetType();
  template<> int GetType<bool>()    { return UA_TYPES_BOOLEAN; }
  template<> int GetType<char>()    { return UA_TYPES_SBYTE; }
  template<> int GetType<byte>()    { return UA_TYPES_BYTE; }
  template<> int GetType<Int16>()   { return UA_TYPES_INT16; }
  template<> int GetType<UInt16>()  { return UA_TYPES_UINT16; }
  template<> int GetType<Int32>()   { return UA_TYPES_INT32; }
  template<> int GetType<UInt32>()  { return UA_TYPES_UINT32; }
  template<> int GetType<Int64>()   { return UA_TYPES_INT64; }
  template<> int GetType<UInt64>()  { return UA_TYPES_UINT64; }
  template<> int GetType<float>()   { return UA_TYPES_FLOAT; }
  template<> int GetType<double>()  { return UA_TYPES_DOUBLE; }
  template<> int GetType<String^>() { return UA_TYPES_STRING; }
  static std::string ConvertToStandardString(String^ managedStr);

  ILog^ m_log; // My log4net logger
  Logger * m_logger;
  UA_Client * m_client;
  bool m_connected;
};
```

## LibOpen62541.cpp

```C++
#include "open62541.h"
#include "LibOpen62541.h"
    
LibOpen62541::LibOpen62541() :
  m_log(LogManager::GetLogger("Lemoine.Cnc.LibOpen62541")), // My custom logger
  m_logger(new Logger(m_log)), // The interface for open62541
  m_client(NULL),
  m_connected(false)
{}

LibOpen62541::!LibOpen62541()
{
  // Disconnect client and destroy it
  if (m_client) {
    if (m_connected)
      UA_Client_disconnect(m_client);
    UA_Client_delete(m_client);
    m_client = NULL;
  }
  m_connected = false;
  
  // Free unmanaged logger
  delete m_logger;
  m_logger = NULL;
}

bool LibOpen62541::Connect(String^ hostAddress)
{
  // Client configuration and creation
  if (!m_client) {
    m_client = UA_Client_new(UA_ClientConfig_standard, m_logger->GetLogger());
    if (m_client == NULL) {
      m_log->ErrorFormat("Failed to create a client");
      return false;
    }
  }
  
  // Connection if necessary
  if (m_client && !m_connected) {
    UA_StatusCode retVal = UA_Client_connect(m_client, ClientNetworkLayerTCP_connect,
      (char *)ConvertToStandardString(hostAddress).c_str());
    if (retVal == UA_STATUSCODE_GOOD) {
      m_connected = true;
      m_log->InfoFormat("Connection to: {0} => success", hostAddress);
    } else
      m_log->ErrorFormat("Connection to: {0} => error {1}", hostAddress, (int)retVal);
  }

  return m_connected;
}

// Generic "Get", for all types described in the template instanciations (listed below)
template<typename T> T LibOpen62541::Get(String^ parameter) 
{
  T valRet = 0;
  if (!m_connected)
    return valRet;

  UA_ReadRequest req;
  UA_ReadRequest_init(&req);
  req.nodesToRead = (UA_ReadValueId*)UA_ReadValueId_new();
  req.nodesToReadSize = 1;
  req.nodesToRead[0].nodeId = UA_NodeId_fromCharStringCopy(1, ConvertToStandardString(parameter).c_str());
  req.nodesToRead[0].attributeId = UA_ATTRIBUTEID_VALUE;

  UA_ReadResponse resp = UA_Client_read(m_client, &req);
  const UA_DataType * expectedType = &UA_TYPES[GetType<T>()];
  if (resp.responseHeader.serviceResult == UA_STATUSCODE_GOOD && resp.resultsSize > 0 && resp.results[0].hasValue &&
    UA_Variant_isScalar(&resp.results[0].value) && resp.results[0].value.type == expectedType) {
    valRet = *(T*)resp.results[0].value.data;

    UA_ReadRequest_deleteMembers(&req);
    UA_ReadResponse_deleteMembers(&resp);
  } else {
    String^ error = "Cannot get the value " + parameter + ":\n" +
      "Service result = {0}\n" +
      "Result size = {1}\n" +
      "Has value = {2}\n" +
      "Is scalar = {3}\n" +
      "Type match = {4}";
    if (resp.resultsSize > 0)
      m_log->ErrorFormat(error, (int)resp.responseHeader.serviceResult, resp.resultsSize,
        resp.results[0].hasValue, UA_Variant_isScalar(&resp.results[0].value),
        expectedType == resp.results[0].value.type);
    else
      m_log->ErrorFormat(error, (int)resp.responseHeader.serviceResult, resp.resultsSize, "-", "-", "-");

    UA_ReadRequest_deleteMembers(&req);
    UA_ReadResponse_deleteMembers(&resp);
    throw gcnew Exception("Cannot get the value " + parameter);
  }

  return valRet;
}
template bool LibOpen62541::Get<bool>(String^ parameter);
template char LibOpen62541::Get<char>(String^ parameter);
template byte LibOpen62541::Get<byte>(String^ parameter);
template Int16 LibOpen62541::Get<Int16>(String^ parameter);
template UInt16 LibOpen62541::Get<UInt16>(String^ parameter);
template Int32 LibOpen62541::Get<Int32>(String^ parameter);
template UInt32 LibOpen62541::Get<UInt32>(String^ parameter);
template Int64 LibOpen62541::Get<Int64>(String^ parameter);
template UInt64 LibOpen62541::Get<UInt64>(String^ parameter);
template float LibOpen62541::Get<float>(String^ parameter);
template double LibOpen62541::Get<double>(String^ parameter);

// Specialization of the method "Get" for the type String^
template<> String^ LibOpen62541::Get<String^>(String^ parameter) 
{
  String^ valRet = "";
  if (!m_connected)
    return valRet;

  // TO BE IMPLEMENTED

  return valRet;
}

std::string LibOpen62541::ConvertToStandardString(String^ managedStr)
{
  std::string strTmp;
  strTmp.resize(managedStr->Length + 1);
  for (int i = 0; i < managedStr->Length; i++)
    strTmp[i] = (char)managedStr[i];
  strTmp[managedStr->Length] = '\0';
  return strTmp;
}
```

## Logger.h

```C++
#pragma once

#include "open62541.h"
#include "Windows.h"
using namespace log4net;
using namespace System::Runtime::InteropServices;

// This class is created with an instance of a managed logger
// It provides then a callback suitable for open62541
class Logger
{
public:
  Logger(ILog^ managedLogger);
  ~Logger(void);
  UA_Logger GetLogger();

private:
  GCHandle m_logHandle;
};
```

## Logger.cpp

```C++
#include "Logger.h"
#include <string>
using namespace System;

// Two levels for the callback because functions with variable arguments
// cannot comprise managed types (such as the log4net logger)
static void * LOG_HANDLE = NULL;
static const int BUFFER_LENGTH = 256;
static void LOG_LEVEL_2(UA_LogLevel level, UA_LogCategory category, const char *msg)
{
  if (LOG_HANDLE) {
    // Retrieve the managed logger
    using System::Runtime::InteropServices::GCHandle;
    GCHandle gch = GCHandle::FromIntPtr((IntPtr)LOG_HANDLE);
    ILog^ log = (ILog^)gch.Target;

    // Preparation of the message
    String ^text = "[Open62541, ";
    switch (category) {
    case UA_LOGCATEGORY_COMMUNICATION:  text += "communication"; break;
    case UA_LOGCATEGORY_SERVER:         text += "server"; break;
    case UA_LOGCATEGORY_CLIENT:         text += "client"; break;
    case UA_LOGCATEGORY_USERLAND:       text += "userland"; break;
    }
    text += "] " + gcnew String(msg);

    // Dispatch the message according to the severity level
    switch (level) {
    case UA_LOGLEVEL_INFO:    log->Info(text);  break;
    case UA_LOGLEVEL_WARNING: log->Warn(text);  break;
    case UA_LOGLEVEL_ERROR:   log->Error(text); break;
    case UA_LOGLEVEL_FATAL:   log->Fatal(text); break;
    default:                  log->Debug(text); break;
    }
  }
}

#pragma unmanaged // Remove warning C4793: 'anonymous namespace' for LOGGER
#pragma warning(disable: 4996) // Disable deprecation (vsnprintf function)
static void LOG_LEVEL_1(UA_LogLevel level, UA_LogCategory category, const char *format, ...)
{
  char buffer[BUFFER_LENGTH];
  va_list args;
  va_start(args, format);
  vsnprintf(buffer, BUFFER_LENGTH, format, args);
  LOG_LEVEL_2(level, category, buffer);
  va_end(args);
}
#pragma warning(default: 4996) // Restore deprecation
#pragma managed

Logger::Logger(ILog^ managedLogger)
{
  // Create a handle on the logger, accessible from unmanaged code
  m_logHandle = GCHandle::Alloc(managedLogger);
  IntPtr pointer = GCHandle::ToIntPtr(m_logHandle);
  LOG_HANDLE = pointer.ToPointer();
}

Logger::~Logger()
{
  // Free the handle on the log
  // The object targeted can now be garbage collected if there is no more references to it
  m_logHandle.Free();
}

UA_Logger Logger::GetLogger()
{
  return LOG_LEVEL_1;
}
```

# Usage

Using this library (assembly) in a C# project, you will be able to:
* create a new LibOpen62541(),
* call the method Connect with "opc.tcp://localhost:16664" as argument,
* display the value returned by Get < Int32 > ("the.answer"), which should be 42 if the server provided as example is used.

The dll "open62541.dll" has to be in the project directory, or found via the path.

**Comment by Stasik0** [comment]
@davy7125 woooow! that a huge amount of work you have done! Two questions:
* did the supplied libopen62541.dll not work?
* what do you think would be a best practice to spread these files? Via repository, and a project file? Or just copy-pasting it somewhere?

**Comment by davy7125** [comment]
Implicit linking on Windows requires a .lib file along with the .dll file (contrary to linux which only needs a .so file). This is explained [here](https://msdn.microsoft.com/en-us/library/253b8k2c.aspx).
Maybe you built the library with mingw? I'm not sure but I think mingw don't need .lib and this might be the cause of the missing .lib.

I didn't try explicit linking with libopen62541.dll since it's a longer method and also because I had a memory violation error in a C# project using it.

I don't know either what is the best way to spread and improve this unaccomplished work. Your role is to provide the library, and every user will then have to integrate it. Several ways for this, several languages... You can't cope with all that stuff. The code I wrote is already specialized by the use of the interface ILog, which is specific to my project.

For sure it has to be kept, but more like a source of inspiration or even a template if it becomes more generic. I'll work on the Get method as you asked.

A little question: is it the same way to retrieve a UA_String than to retrieve a UA_Int32 or any other type?

**Comment by Stasik0** [comment]
@davy7125: do yo mean by a readValue? Yes same way. The resulting string is a bit different from cstring its is a struct with a pointer to byte and a length (https://github.com/acplt/open62541/blob/a7482ed0a66ac2f95f7f00b3f4eb1b26a134faed/include/ua_types.h#L113).

Regarding dlls: we do not even use mingw, instead windows binaries are cross-compiled on linux. There should be this lib file included in the releases (libopen62541.dll.a).

Regarding your custom ILog interface, so our way would be to create an own logger interface and probably a reference implementation?

**Comment by davy7125** [comment]
Using libopen62541.dll.a resulted in link errors. I'm thus still using the .dll and .lib I built myself.

The code should now be able to query with integers and guids. The namespace index can be changed.
I introduced the interface ILogger, this is now generic and it looks better.

I just saw a possible bug by converting UA_String into String^, I will change the code soon.

**Comment by Stasik0** [comment]
I'd like to have an example project file on that under "bindings"

**Comment by jpfr** [comment]
parts of the project are nice and compliant.
new bindings will not be. at least initially.
we need to make clear what parts of the project are in what shape.

**Comment by Stasik0** [comment]
yea but we need at least some "entry points", maybe spawning an open62541-bindings repository?

**Comment by ichrispa** [comment]
We are having some problems getting the c-header def's from open62541 into C# code under MSWin/VS2015. 
@davy7125: Can you give me an example of how you managed that?

**Comment by jpfr** [comment]
We now have continuous integration testing for C++.

**Comment by klasik16** [comment]
Hello it is available somewhere Creating a C++ / CLI project for download?
