### ISSUE TITLE
Create a list of features of the current server / client

### ISSUE THREAD

**Issue by Stasik0** [acplt/open62541#243]
Probably as a wiki page, I love such feature lists since one can check, whether a project meets ones requirements.

**Comment by jpfr** [comment]
Yes!
Also, put it on the homepage.
We can also use the feature list to structure the documentation and link from the homepage into doxygen.

**Comment by Stasik0** [comment]
Started here: https://github.com/acplt/open62541/wiki/Feature-list-of-open62541

**Comment by jpfr** [comment]
I removed the bindings entry.
Most of them aren't anywhere near completion.

Let's put them on the features list when they are actually usable and part of the (supported) main code base.
