### ISSUE TITLE
ERROR - Server did not return an EndpointDescription that matched the one used to create the secure channel.

### ISSUE THREAD

**Issue by jpfr** [acplt/open62541#249]
Patrick Meijers reported issues with some clients.
https://groups.google.com/forum/#!topic/open62541/aE6eYrtZCog

Let's fix that before the 0.1 release!

**Comment by Stasik0** [comment]
For the softing issue, i suspect that listening on all interfaces is a problem. After the accept we need to find out the ip/hostname the client is talking to (or maybe it is in the opc ua message?) and to output this address in endpoint list. 

Regarding the sdk, it looks like the client is forcing a username/pass login so it may be a configuration issue.

**Comment by Stasik0** [comment]
seems to be fixed in the master the answer to the c++ sdk issue ist in the group.
