### ISSUE TITLE
check python install

### ISSUE THREAD

**Issue by HolgerJeromin** [acplt/open62541#263]
open62541 needs a python and python-lxml install (always?) so it would be nicer to check the availability somewhere. Otherwise you get a ugly abort from make.
This is especially important for windows...

**Comment by Stasik0** [comment]
You need em to generate code from xml files. Checking for py in cmake is easy, does anyone have a snipplet for checking for lxml?

**Comment by HolgerJeromin** [comment]
Thank you @bilach and Stasik0!

**Comment by Stasik0** [comment]
@ichrispa is your srcipt runnable with Pyhton 3? or is it 2.7 only?

**Comment by HolgerJeromin** [comment]
@Stasik0: did you meant chris or bilach?
My windows machine has this output:

```
Found PythonInterp: C:/Program Files (x86)/python/python.exe (found version "3.4.3") 
  File "<string>", line 1
    from distutils.sysconfig import get_python_lib; print get_python_lib()
                                                                       ^
SyntaxError: invalid syntax

CMake Error at CMakeLists.txt:11 (message):
  Python-lxml is not installed.
```
So whole thing is not optimal right now :-)
We probaby should use `PYTHON_EXECUTABLE`.

**Comment by Stasik0** [comment]
i meant @ichrispa and his ns0 generation script, they may not run with py3 at all. 
@HolgerJeromin could you tweak a bit on the script in CMakeLists?
