### ISSUE TITLE
Get a Windows build going

### ISSUE THREAD

**Issue by Stasik0** [acplt/open62541#280]
There is a Travis-Ci clone for windows-based VMs:

http://www.appveyor.com/

At least we can get builds (compiling with msvs 2015) running there.

**Comment by ichrispa** [comment]
Interesting... all our attempts to use MSVS2015 failed due to limited c99 support when expanding macros.

**Comment by Stasik0** [comment]
yea, but cannot you workaround it somehow?

**Comment by ichrispa** [comment]
I need to switch my development focus from linux/stack dev to windows application dev soon. Windows is unfortunately a requirement due to third party dependencies. I'll see what I can do in the coming days.

**Comment by Stasik0** [comment]
@ichrispa we need to workaround it anyway. Here: http://blogs.msdn.com/b/vcblog/archive/2015/04/29/c-11-14-17-features-in-vs-2015-rc.aspx it is stated as "[3] C99 preprocessor support is unchanged.  It's Partial because while the compiler supports variadic macros, our preprocessor's behavior doesn't conform to C99/C++11 in many ways. ". But getting an msvc is very imporant!

**Comment by ichrispa** [comment]
I can't really find out where the fuss is. Maybe my VS2015 is afraid of me and just cooperates.

Turning intellisense off reduces the MSVS build of the master branch to the following problems:
  *  F_OK definitions need to be added to ua_util.h (as in dev several weeks ago)
  * When amalgamation is enabled, MSVS murks up the build order and skips building the header. Some manual fiddeling with the build order is required (place one check mark to make server depend on amalgamation)
  * When amalgamation is enabled, the ua_util.h contents for F_OK are not available to the server. Adding them to server.c fixes that problem.

After that, I have good compiles in the master branch.

**Comment by Stasik0** [comment]
Can't the build order be changed in CMakeList? or will it break the other build?

**Comment by ichrispa** [comment]
@Stasik0: In MSVS: Project->Project Build Order; Select dependencies and "server" from the dropdown list. Add amalgamation as a dependency.

The Development branch had two added pains; there was a stray `COMMAND python` in the CMakeFile and a cast in subscriptions.c was a problem for MSVS ("Cannot cast UA_Job to UA_Job"). Both have been fixed.
