### ISSUE TITLE
Amalgamation has multiple file includes

### ISSUE THREAD

**Issue by Stasik0** [acplt/open62541#282]
Amalgamation script seems to include ua_config.h one time in open62541.h und *two* times in open62541.c :/ Therefore, some variables were always set, I worked-around it in 4fb5e8a1a059c1cc00986bb91cb456bfc1c6adbe, however this behavior is not tolerable. We need to clean up amalgamation to prevent such stuff.

**Comment by jpfr** [comment]
Fixed in df4753b00d74b21f8a76e644fc63d9e5d1564206
