### ISSUE TITLE
Documentation Reset

### ISSUE THREAD

**Issue by jpfr** [acplt/open62541#285]
Dear all,

currently, open62541 is nearly impossible to use for somebody who does not want to read the actual sources. Besides the raw Doxygen definitions, we should have more prose in the documentation.

Please have a look at http://open62541.org/doc/sphinx/
The existing doxygen definitions can be easily referenced. The source of the pages is
- https://raw.githubusercontent.com/acplt/open62541/master/doc/index.rst
- https://raw.githubusercontent.com/acplt/open62541/master/doc/datatypes.rst

The structure could look llike this.

1. Introduction
   - Information Model
2. DataTypes
3. Services
4. Server
  - Startup
  - Adding Variables
  - Adding Methods
5. Client

Anything else?

**Comment by Stasik0** [comment]
is there some tutorial on this magic markup?

**Comment by jpfr** [comment]
http://sphinx-doc.org/contents.html
https://breathe.readthedocs.org/en/latest/directives.html

**Comment by FlorianPalm** [comment]
Interface to external nodestores?

**Comment by Stasik0** [comment]
Configuration options: https://github.com/acplt/open62541/wiki/Configuration-options, probably it is better to remove them from the wiki and transfer to sphinx

**Comment by jpfr** [comment]
http://open62541.org/doc/sphinx/building.html

**Comment by jpfr** [comment]
@Stasik0 told me about this Sphinx documentation: http://thrift-tutorial.readthedocs.org/en/latest/intro.html

That is really well made! Should we simply copy their structure?

**Comment by Stasik0** [comment]
I'd also like to have some "articles" section that are more or less blog posts on various topics

**Comment by jpfr** [comment]
Yeah!
So we have a series of articles to build up basic understanding and a separate "API documentation" with inline code examples.

@Stasik0 you have some themes for articles in mind?

**Comment by Stasik0** [comment]
You had a couple of artcles un your blog :)))

**Comment by ichrispa** [comment]
Is there room in the documentation for a tutorial on open62541? Something to talk new users through creating server/client applications, datasources on variable nodes, callbacks in methods and monitoreditems an such?

**Comment by jpfr** [comment]
> I went on a limb and wrote a firstSteps.rst

Just perfect. :smile:

**Comment by jpfr** [comment]
The new infrastructure is in place.
Now we need to write the content. :-)
