### ISSUE TITLE
Canonical examples instead of "big mess examples"

### ISSUE THREAD

**Issue by jpfr** [acplt/open62541#294]
I started to add many "small" server examples, each showing a single feature.

https://github.com/acplt/open62541/blob/master/examples/server_variable.c
https://github.com/acplt/open62541/blob/master/examples/server_method.c
https://github.com/acplt/open62541/blob/master/examples/server_repeated_job.c

Adding another example is just a two-liner here: https://github.com/acplt/open62541/blob/master/examples/CMakeLists.txt

Since the examples are an important part of the documentation, we imho should get rid of the big example servers and split everything into canonical and understandable mini-examples.

**Comment by HolgerJeromin** [comment]
I like it!

**Comment by Stasik0** [comment]
we need to add examples to the build-chain in order to ensure the consistency of the api

**Comment by Stasik0** [comment]
i added server_nodeset.c

**Comment by Stasik0** [comment]
refers to #285
