### ISSUE TITLE
Cannot compile with ENABLE_AMALGAMATION and ENABLE_SUBSCRIPTION

### ISSUE THREAD

**Issue by Stasik0** [acplt/open62541#299]
Errors give something like:

```
In file included from /home/sten/Desktop/open62541/open62541.c:25:0:
/home/sten/Desktop/open62541/open62541.h:4183:5: error: expected specifier-qualifier-list before ‘LIST_ENTRY’
     LIST_ENTRY(UA_Client_NotificationsAckNumber_s) listEntry;
     ^
```
etc

**Comment by ichrispa** [comment]
I think the order of inclusion of queue.h and subscriptions.h might be messed up; is #define LIST_ENTRY(field) above that line in amalgamation?

**Comment by Stasik0** [comment]
okay the problem is that queue.h is not included in the public header files. @jpfr @ichrispa I think it would be better if we would introduce ua_client_internal aswell to hide all the client's gutts like its done with the server. Does it make sense?

**Comment by jpfr** [comment]
>  introduce ua_client_internal aswell to hide all the client's gutts

Good idea!

**Comment by ichrispa** [comment]
> Does it make sense?

Yep, I'd support that.
