### ISSUE TITLE
Use PCG Random Number generator

### ISSUE THREAD

**Issue by jpfr** [acplt/open62541#300]
The latest cygwin patch worked around the differences in the random number generator across operating systems.

We could simply roll our own PCG-based RNG.
http://www.pcg-random.org/download.html

- literally 5 lines of code
- nicer randomness than the builtin RNG
- removes another friction point for porting

Currently, we store the seed in the server struct. For concurrency, we should declare it as thread local storage. So threads don't interfere / cache-congest.

**Comment by ichrispa** [comment]
@jpfr: Would this also replace rand_r from stdlib.h in ua_types.c?

I am trying to compile open62541 for android-17 and the subminimal support of libc is turning out to be a problem...

But I am happy to report that the stack runs great on my Kobo Touch eBook Reader - I don't know what use that will be, but it proves we are in principal still ok on ARM targets :)

**Comment by Stasik0** [comment]
@ichrispa afaik, it will

**Comment by DuhaNN** [comment]
@ichrispa can you help me with android? Do you have wrapper? Thanks

**Comment by jpfr** [comment]
The change was implemented in 85cd217.
