### ISSUE TITLE
UA_NODEID_BYTESTRING_ALLOC -- possible error?

### ISSUE THREAD

**Issue by tpiat** [acplt/open62541#307]
Probably I don't understand this, but 
UA_NODEID_BYTESTRING(NS_INDEX, CHARS) defined as 
UA_NodeId_from<B>CharByte</B>String(NS_INDEX, CHARS)
                            
and 
UA_NODEID_BYTESTRING_ALLOC(NS_INDEX, CHARS)  defined as 
UA_NodeId_from<B>Char</B>StringCopy(NS_INDEX, CHARS)
instead
UA_NodeId_from<B>CharByte</B>StringCopy(NS_INDEX, CHARS)
Is this a error?

**Comment by Stasik0** [comment]
Yes in theory, but we currently map strings to bytestrings internally so it works as expected ;) thank you for reporting.
