### ISSUE TITLE
Problem build in Visual Studio 2013

### ISSUE THREAD

**Issue by Kal-elpatch** [acplt/open62541#316]
Hi guys!
I  build the open62541.sln with CMAKE gui, but occurs this error when compile

error MSB6006: "cmd.exe" exited with code 9009.	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets	170	5	open62541-object

Someone can help me please?

**Comment by Stasik0** [comment]
Which branch are you using? Which msvs version are you using?

**Comment by Kal-elpatch** [comment]
I use Microsoft Visual Studio Ultimate  2013  Version 12.0.31101.00 Update 4
I download the source code from
http://open62541.org/ .zip Button
and from
https://github.com/acplt/open62541.git

**Comment by Kal-elpatch** [comment]
Master branch sorry

**Comment by Stasik0** [comment]
Afaik open62541 builds only with msvs 15 due to the lack of c99 support in the older versions :( Master is compiled with vs15 by our ci server.

**Comment by Kal-elpatch** [comment]
Thanks :)
