### ISSUE TITLE
ReferenceTypeId?

### ISSUE THREAD

**Issue by Hexsc** [acplt/open62541#318]
Hi!

For what exactly is the referenceTypeId in various functions required?
I found no use for it until now.

Thanks in advance for your always very helpful answers.
Regards,
Hexsc

**Comment by FlorianPalm** [comment]
If you would like to create a node within the address space of the server you need to specify how this new node is connected to other nodes. There are many different types of references, e.g., Organizes HasComponent, HasProperty etc. 
Every reference is identified by a nodeId i.e. ReferenceTypeId

**Comment by Hexsc** [comment]
@FlorianPalm thank you very much! :+1:
