### ISSUE TITLE
DataSource Variable works on Windows but not on Linux - invalid free

### ISSUE THREAD

**Issue by martina-felber** [acplt/open62541#320]
Hello!

I've tried to define a datasource variable node, which increments a value on each read and offers a write function to set the value of the variable to the given param. I copied your example code which adds the "current time" data source variable. Your example works finde on Windows and Linux. But my defined data source variable works only on Windows and crashes on Linux (openSUSE 13.1). Valgrind states that the server frees an invalid pointer. I am using the master branch (downloaded it today).

Server Code main():
```C
	// add data source variable "Inc_And_Set"
	// at each read the value is incremented
	// with a write call the value can be set to the input param
	UA_Int32 Inc_And_Set_Value = -1;
	UA_DataSource Inc_And_Set_Source = (UA_DataSource) {
					.handle = &Inc_And_Set_Value,
					.read = IncValue,
					.write = SetValue};
	UA_Server_addDataSourceVariableNode(server, Inc_And_Set_Source,
			UA_QUALIFIEDNAME(1, "Inc_And_Set"), UA_NODEID_STRING(1, "Inc_And_Set"),
			UA_NODEID_NUMERIC(0, UA_NS0ID_OBJECTSFOLDER), UA_NODEID_NUMERIC(0, UA_NS0ID_ORGANIZES), NULL);
```
Server Code IncValue():
```C
/* UA_DataSource .read function
 * increments value of handle at each call
 */
UA_StatusCode IncValue(void *handle, UA_Boolean includeSourceTimeStamp,
		const UA_NumericRange *range, UA_DataValue *value) {
	printf("IncValue call() \n");
	if(range) {
		value->hasStatus = UA_TRUE;
		value->status = UA_STATUSCODE_BADINDEXRANGEINVALID;
		return UA_STATUSCODE_GOOD;
	}

	if(handle != 0 && value != 0) {
		UA_Int32* pValue = (UA_Int32*) handle;

		value->value.type = &UA_TYPES[UA_TYPES_INT32];
		value->value.arrayLength = -1;
		value->value.data = pValue;
		value->hasValue = UA_TRUE;

		if(includeSourceTimeStamp) {
			value->hasSourceTimestamp = UA_TRUE;
			value->sourceTimestamp = UA_DateTime_now();
		}
		(*pValue)++;
		printf("return good \n");
		return UA_STATUSCODE_GOOD;
	}
	printf("return error \n");
	return UA_STATUSCODE_BADARGUMENTSMISSING; // don't know which error code to use
}
```

Client Code main() - ReadRequest:
```C
    ////////////////////////////////////////////////////////////////////////////////////
    // read datasource variable "Inc_And_Set"
    printf("\nRead Inc_And_Set value: ");
    UA_Int32 * pValue = 0;
    UA_ReadRequest_init(&rReq);
    rReq.nodesToRead = UA_ReadValueId_new();
    rReq.nodesToReadSize = 1;
    rReq.nodesToRead[0].nodeId = UA_NODEID_STRING_ALLOC(1, "Inc_And_Set");
    rReq.nodesToRead[0].attributeId = UA_ATTRIBUTEID_VALUE;

    rResp = UA_Client_read(client, &rReq);
    if(rResp.responseHeader.serviceResult == UA_STATUSCODE_GOOD &&
       rResp.resultsSize > 0 && rResp.results[0].hasValue &&
       UA_Variant_isScalar(&rResp.results[0].value) &&
       rResp.results[0].value.type == &UA_TYPES[UA_TYPES_INT32]) {

    	pValue = (UA_Int32*)rResp.results[0].value.data;
        printf("%i\n", *pValue);
    }

    UA_ReadRequest_deleteMembers(&rReq);
    UA_ReadResponse_deleteMembers(&rResp);
```

/////////////////////////////////////////////////////////////////////////////////////////////////
server output:
user@linux:~/AM335x-052-eglibc/eclipse/workspace/opc_linux_datasource_server/Debug> ./opc_linux_datasource_server 
[08/11/2015 08:28:48.839.887] info/communication        Listening on opc.tcp://linux.site:16664
IncValue call() 
return good 
*** Error in `./opc_linux_datasource_server': free(): invalid pointer: 0xbf81f854 ***
======= Backtrace: =========
/lib/libc.so.6(+0x6dfd3)[0xb763bfd3]
/lib/libc.so.6(+0x7418a)[0xb764218a]
/lib/libc.so.6(+0x74dcc)[0xb7642dcc]
./opc_linux_datasource_server[0x804c133]
./opc_linux_datasource_server[0x804a950]
./opc_linux_datasource_server[0x804a760]
./opc_linux_datasource_server[0x804be64]
./opc_linux_datasource_server[0x804bc7a]
./opc_linux_datasource_server[0x804c111]
./opc_linux_datasource_server[0x804bdad]
./opc_linux_datasource_server[0x804bc7a]
./opc_linux_datasource_server[0x8059e3c]
./opc_linux_datasource_server[0x805a58d]
./opc_linux_datasource_server[0x805b097]
./opc_linux_datasource_server[0x805bb3e]
./opc_linux_datasource_server[0x805c2f4]
./opc_linux_datasource_server[0x805c36e]
./opc_linux_datasource_server[0x80695f8]
/lib/libc.so.6(__libc_start_main+0xf3)[0xb75e79d3]
./opc_linux_datasource_server[0x8048c11]
======= Memory map: ========
08048000-08070000 r-xp 00000000 08:11 1573922    /home/user/AM335x-052-eglibc/eclipse/workspace/opc_linux_datasource_server/Debug/opc_linux_datasource_server
08070000-08071000 r--p 00027000 08:11 1573922    /home/user/AM335x-052-eglibc/eclipse/workspace/opc_linux_datasource_server/Debug/opc_linux_datasource_server
08071000-08074000 rw-p 00028000 08:11 1573922    /home/user/AM335x-052-eglibc/eclipse/workspace/opc_linux_datasource_server/Debug/opc_linux_datasource_server
09282000-092be000 rw-p 00000000 00:00 0          [heap]
b7595000-b75b0000 r-xp 00000000 08:02 2360406    /lib/libgcc_s.so.1
b75b0000-b75b1000 r--p 0001a000 08:02 2360406    /lib/libgcc_s.so.1
b75b1000-b75b2000 rw-p 0001b000 08:02 2360406    /lib/libgcc_s.so.1
b75cd000-b75ce000 rw-p 00000000 00:00 0 
b75ce000-b7779000 r-xp 00000000 08:02 2360275    /lib/libc-2.18.so
b7779000-b777b000 r--p 001ab000 08:02 2360275    /lib/libc-2.18.so
b777b000-b777c000 rw-p 001ad000 08:02 2360275    /lib/libc-2.18.so
b777c000-b777f000 rw-p 00000000 00:00 0 
b7798000-b779b000 rw-p 00000000 00:00 0 
b779b000-b779c000 r-xp 00000000 00:00 0          [vdso]
b779c000-b77bd000 r-xp 00000000 08:02 2366371    /lib/ld-2.18.so
b77bd000-b77be000 r--p 00020000 08:02 2366371    /lib/ld-2.18.so
b77be000-b77bf000 rw-p 00021000 08:02 2366371    /lib/ld-2.18.so
bf800000-bf821000 rw-p 00000000 00:00 0          [stack]
Abgebrochen

/////////////////////////////////////////////////////////////////////////////////////////////////
client output:
user@linux:~/AM335x-052-eglibc/eclipse/workspace/opc_linux_datasource_client/Debug> ./opc_linux_datasource_client 

Read current time: 08/11/2015 08:27:05.654.631.000

Read Inc_And_Set value: 5

Client finished

/////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////
Server output with valgrind:
user@linux:~/AM335x-052-eglibc/eclipse/workspace/opc_linux_datasource_server/Debug> valgrind --leak-check=yes ./opc_linux_datasource_server 
==5585== Memcheck, a memory error detector
==5585== Copyright (C) 2002-2012, and GNU GPL'd, by Julian Seward et al.
==5585== Using Valgrind-3.8.1 and LibVEX; rerun with -h for copyright info
==5585== Command: ./opc_linux_datasource_server
==5585== 
[08/11/2015 08:30:08.696.611] info/communication        Listening on opc.tcp://linux.site:16664
IncValue call() 
return good 
==5585== Invalid free() / delete / delete[] / realloc()
==5585==    at 0x402B1DD: free (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)
==5585==    by 0x804A94F: UA_Variant_deleteMembers (open62541.c:2708)
==5585==    by 0x804A75F: UA_DataValue_deleteMembers (open62541.c:2660)
==5585==    by 0x804BE63: UA_deleteMembersUntil (open62541.c:3280)
==5585==    by 0x804BC79: UA_deleteMembers (open62541.c:3215)
==5585==    by 0x804C110: UA_Array_delete (open62541.c:3361)
==5585==    by 0x804BDAC: UA_deleteMembersUntil (open62541.c:3238)
==5585==    by 0x804BC79: UA_deleteMembers (open62541.c:3215)
==5585==    by 0x8059E3B: invoke_service (open62541.c:7802)
==5585==    by 0x805A58C: processMSG (open62541.c:7927)
==5585==    by 0x805B096: UA_Server_processBinaryMessage (open62541.c:8045)
==5585==    by 0x805BB3D: processJobs (open62541.c:8435)
==5585==  Address 0xbedd2ce4 is on thread 1's stack
==5585== 
^C[08/11/2015 08:30:56.961.156] info/server     Received Ctrl-C

==5585== 
==5585== HEAP SUMMARY:
==5585==     in use at exit: 0 bytes in 0 blocks
==5585==   total heap usage: 914 allocs, 915 frees, 830,612 bytes allocated
==5585== 
==5585== All heap blocks were freed -- no leaks are possible
==5585== 
==5585== For counts of detected and suppressed errors, rerun with: -v
==5585== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
user@linux:~/AM335x-052-eglibc/eclipse/workspace/opc_linux_datasource_server/Debug> 

/////////////////////////////////////////////////////////////////////////////////////////////////
Client output with valgrind:
user@linux:~/AM335x-052-eglibc/eclipse/workspace/opc_linux_datasource_client/Debug> valgrind --leak-check=yes ./opc_linux_datasource_client 
==5588== Memcheck, a memory error detector
==5588== Copyright (C) 2002-2012, and GNU GPL'd, by Julian Seward et al.
==5588== Using Valgrind-3.8.1 and LibVEX; rerun with -h for copyright info
==5588== Command: ./opc_linux_datasource_client
==5588== 

Read current time: 08/11/2015 08:30:17.470.943.000

Read Inc_And_Set value: 0

Client finished

==5588== 
==5588== HEAP SUMMARY:
==5588==     in use at exit: 0 bytes in 0 blocks
==5588==   total heap usage: 79 allocs, 79 frees, 1,446,625 bytes allocated
==5588== 
==5588== All heap blocks were freed -- no leaks are possible
==5588== 
==5588== For counts of detected and suppressed errors, rerun with: -v
==5588== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
user@linux:~/AM335x-052-eglibc/eclipse/workspace/opc_linux_datasource_client/Debug> 

Many thanks for your help.
Best regards
Martina

**Comment by Stasik0** [comment]
As far as I understand it you will need to allocate memory for the data value and copy it into it.
The server tries to free this pointer after the response has been sent and crashes.
So instead of passing a pointer to handle to value.data as in ```value->value.data = pValue;``` try to allocate ```UA_Int32* pValue = UA_Int32_new();``` and copy the value. Since the last implementation, the user has to do it manually.

**Comment by martina-felber** [comment]
Many thanks for your hint!
