### ISSUE TITLE
Subscription timestamp problem

### ISSUE THREAD

**Issue by StalderT** [acplt/open62541#324]
Hello,

I use the server in git examples directory.

If I browser the "current time" variable with UAExpert :

1) With subscription I have no timestamp.

2) If I read the variable I have timestamp.

You can see the result :

![timestamp](https://cloud.githubusercontent.com/assets/13799456/9277743/6159d8e6-42ac-11e5-87da-258225f87277.png)

Is it normal ?

**Comment by Stasik0** [comment]
requiring @ichrispa

**Comment by ichrispa** [comment]
Will look into it.

**Comment by ichrispa** [comment]
In theory, this is an error of uaexpert; Data Change notifications are never sent with a timestamp (so showing them is an error in itself). I can easily enable server timestamps; source timestamps are currently meaningless, as without an event system there is no possible way a sample in a queue can have any other timestamp then the servers timestamp.

**Comment by StalderT** [comment]
Hello,

I have test with the patch https://github.com/acplt/open62541/commit/b7c997a9f923a1eebd36ed48e93ba205e78ebc16

The result are : 

![capture_new2](https://cloud.githubusercontent.com/assets/13799456/9383598/b10d401a-474a-11e5-8394-47188dcce136.PNG)

The second variable is on a another OPC UA server (not open62541).

You can see that sourceTimestamp are updated to.

**Comment by Stasik0** [comment]
@ichrispa the pragmatic way would be to assume that source time=server time as its probably done in the other server

**Comment by ichrispa** [comment]
fixed in hl branch
