### ISSUE TITLE
Matrix read SIGSEGV

### ISSUE THREAD

**Issue by tpiat** [acplt/open62541#356]
I want to read matrix from server.

I dont know what data i have read, and I receive SISEGV. What is it?
Array of array or something else?

And I see null pointer in resp.result.value.arrayDimension. But I was expected real pointed, and values 3 and 3. arrayDimensionSize is equal 2, that is correct.

**Comment by FlorianPalm** [comment]
Could you please show the relevant part of your code?

**Comment by tpiat** [comment]
```
UA_ReadResponse rResp = UA_Client_read(node.client, node.rReq);	
```

**Comment by FlorianPalm** [comment]
That did not really enlighten me... perhaps the part where you fill up node.rReq?

**Comment by tpiat** [comment]
I wrote full the code in #348.
I see values in debugger.

**Comment by Stasik0** [comment]
we may also have a bug, since there is #355 :/

**Comment by tpiat** [comment]
I can't read not only string,

**Comment by tpiat** [comment]
Tested. Works in short time.
