### ISSUE TITLE
Subscriptions: Republish service is missing

### ISSUE THREAD

**Issue by Stasik0** [acplt/open62541#370]
Just tested our server with Softing OPC UA Client, it tries to invoke Republish service which is not implemented.

**Comment by ichrispa** [comment]
Republish returns not implemented; the client should handle that. If it doesn't, we should create a ticket for the softing client dev team.

**Comment by Stasik0** [comment]
probably another way would be just to implement it, we have to live with some compatibility issues e.g. https://github.com/acplt/open62541/commit/af628ae9af76177b8c517eb28f229999b097576f

**Comment by ichrispa** [comment]
Closed with efae154 which implements republish.
