### ISSUE TITLE
sprintf etc. are not available in all standard libs

### ISSUE THREAD

**Issue by jpfr** [acplt/open62541#387]

**Comment by ichrispa** [comment]
sooo.. this one is closed too, right?

**Comment by jpfr** [comment]
Appveyor still shows some warnings:

    warning C4996: 'sprintf': This function or variable may be unsafe.
    Consider using sprintf_s instead.

**Comment by joerg555** [comment]
The usw of sprintf and strcpy and strcat  is a verry high risk i neuer use it.
we have to make ua_snprintf ... with an implementation in linux w32 ...
I have a solution and will try to publisch it in my fork.

**Comment by jpfr** [comment]
Dependencies on libc have been reduced in the main library. Printf is no longer used.
