### ISSUE TITLE
MinGW Gcc compiles with errors

### ISSUE THREAD

**Issue by tpiat** [acplt/open62541#397]
Releases 156a13b8ff and above are not compiled. (C++) 
93 errors "invalid conversion"

```
static UA_INLINE UA_ReferenceNode * UA_ReferenceNode_new(void) { 
return UA_new(&UA_TYPES[UA_TYPES_REFERENCENODE]); }
```
error: invalid conversion from 'void*' to 'UA_ReferenceNode*'

Must be 
```
static UA_INLINE UA_ReferenceNode * UA_ReferenceNode_new(void) { 
return (UA_ReferenceNode *)UA_new(&UA_TYPES[UA_TYPES_REFERENCENODE]); }
```
Probably, this file for c compiler only, but in this case must be second header file with interfaces only.

**Comment by HolgerJeromin** [comment]
We should catch such things with travis...

**Comment by Stasik0** [comment]
Travis compiled without any problems... it used a cross-compiler...
