### ISSUE TITLE
More callbacks needed

### ISSUE THREAD

**Issue by Stasik0** [acplt/open62541#399]
hey gang, 

we need a callback for a normal variable (not a datasource one) that is called on write, so the user application can get updated. So we will have 3 options for a variable:
* value stored in nodestore
* value stored in nodestore + callbacks returning a copy of the new value if the value is changed by the user ***new one***
* datasource callbacks

everyone okay with that?

**Comment by Stasik0** [comment]
I'd propose just to add another datasource-similar struct (codename UA_CallBack with onRead and onWrite functions) to variable node, so we do have Variant+UA_CallBack or UA_DataSource in the union, kay?

**Comment by jpfr** [comment]
We might need very similar callbacks for subscriptions.
So we don't have to poll the data to find changes.

**Comment by Stasik0** [comment]
yes, this will probably be a part of the "event-like" solution that we need for proper events, anyway.
