### ISSUE TITLE
Array len is invalid for scalar value

### ISSUE THREAD

**Issue by tpiat** [acplt/open62541#401]
Probably it is my bug.
I write integer scalar, i.e. arrayLen= -1;
When I try write it, I have received arrayLen= 1.

UA_Variant_isScalar(data) does not allow change it.
Check it if possible.

**Comment by Stasik0** [comment]
@tpiat using this one?
```
  UA_Variant_setScalarCopy(myIntegerVariant, &myInteger, &UA_TYPES[UA_TYPES_INT32]);
```

**Comment by tpiat** [comment]
Yes

**Comment by Stasik0** [comment]
So, where 1 is reported? I see -1 in ua expert.

**Comment by tpiat** [comment]
But I see 1 in ua expert.
Probably error present in my code.

**Comment by tpiat** [comment]
My error! Sorry...
Thanks for help.
