### ISSUE TITLE
UA_NamespaceGetIndex for Clients

### ISSUE THREAD

**Issue by HolgerJeromin** [acplt/open62541#405]
For implementing the PLCOPEN Client FBs we need the function `UA_NamespaceGetIndex` probably with the prototype
`UA_UINT UA_NamespaceGetIndex(UA_Client *client, UA_String *NamespaceUri);`

**Comment by Stasik0** [comment]
you can look up in the array Server/NamespaceArray or in node (ns=0,i=2255), or you can wrap it up in the function

**Comment by HolgerJeromin** [comment]
Ok, i implement this and try to push it to a nice client function.

**Comment by HolgerJeromin** [comment]
what should be the result if the ns it not found? -1 (so i should return UA_INT) or should i return UA_STATUSCODE and give the function a pointer to UA_UINT?

**Comment by Stasik0** [comment]
probably its better to have a statuscode return
