### ISSUE TITLE
Cache or Device read API

### ISSUE THREAD

**Issue by reza-ebrahimi** [acplt/open62541#407]
how can perform a cache or device read in open62541 API?

**Comment by Stasik0** [comment]
cache or device?

**Comment by reza-ebrahimi** [comment]
Yes, The OPC API provides cache or device mechanism that OPC client can tell OPC server read data from its cache or get data from its original source,

The cache can take less time than device read, because device read goes to fetch data from its source (for example from DCS) and send it to client, but in cache read that was already fetched and stays in memory and OPC server read it from its memory and send to OPC client.

**Comment by Stasik0** [comment]
OPC API is probably not standardized, isn't it? In OPC UA clients can set a maximal age in their request. However these fields are not checked from the server.

**Comment by reza-ebrahimi** [comment]
@Stasik0 Please give me an example.

**Comment by Stasik0** [comment]
Our server currently ignores it. Here is a filed maxAge (https://github.com/acplt/open62541/blob/1a03d0286df8600ddbef372b122e2b17f1b8f8cd/tools/schema/Opc.Ua.Types.bsd#L1419), please look up in the specification of OPC UA what it does mean.

**Comment by reza-ebrahimi** [comment]
@Stasik0 You were thrown a question in my mind, open62541 client can connect with a industrial OPC server such as Yokogawa opc server and interact with it?

**Comment by HolgerJeromin** [comment]
We have successfully connect from the open62541 client to a siemens opc ua server (not DCOM based OPC DA of course).

**Comment by reza-ebrahimi** [comment]
@HolgerJeromin That's good news.

**Comment by Stasik0** [comment]
probably you will have to set the maxAge manually in the ReadRequest of the client

**Comment by reza-ebrahimi** [comment]
@Stasik0 What is the range of maxAge?

**Comment by Stasik0** [comment]
unfortunately, you will have to lookup in the opc ua specification. You can get it from opcfoundation for free, you just need to register

**Comment by reza-ebrahimi** [comment]
@Stasik0 which features in OPC UA standard are not implemented in open62541? Have you a list?

**Comment by Stasik0** [comment]
https://github.com/acplt/open62541/wiki/Feature-list-of-open62541

**Comment by reza-ebrahimi** [comment]
Have any plan for Discovering and Address space browsing functionality in future?

**Comment by Stasik0** [comment]
Browsing is built in of course! didn't you see our demo client

**Comment by reza-ebrahimi** [comment]
@Stasik0 Thanks, but I'm investigating OPC API for my project, so I would like to use open62541, another question is implementation plan for Events in future?

**Comment by FlorianPalm** [comment]
We have in mind to support events. But there is no fixed plan at the moment.
