### ISSUE TITLE
realloc instead UA_realloc

### ISSUE THREAD

**Issue by tpiat** [acplt/open62541#418]
ua_server_addressspace.c
line 1640
used <B>realloc</B> instead <B>UA_realloc</B>

PS. I don't know how to update my files. I made fork a month ago, but now my files is very old. I can't correct this error.

**Comment by Stasik0** [comment]
@tpiat just run "git fetch upstream" in your fork

**Comment by HolgerJeromin** [comment]
Or try to edit the files via Web. As you have no write rights, github will make a clean fresh branch. You can directly make pull request from it. 
For a one liner a quite straight forward work flow.
