### ISSUE TITLE
open62541 client can't connect to MatrikonOPC UA Wrapper for COM Servers

### ISSUE THREAD

**Issue by reza-ebrahimi** [acplt/open62541#420]
open62541 client can't connect to MatrikonOPC UA Wrapper for COM Servers, server status is running and ```UA_Client_connect()``` returns ```UA_STATUSCODE_BADNONCEINVALID```.

```
	UA_Client *client = UA_Client_new(UA_ClientConfig_standard, Logger_Stdout_new());
	UA_StatusCode retval = UA_Client_connect(client, ClientNetworkLayerTCP_connect,
		"opc.tcp://localhost:21381/MatrikonOpcUaWrapper");
	if (retval != UA_STATUSCODE_GOOD) {
		UA_Client_delete(client);
		return retval;
	}
```

**Comment by Stasik0** [comment]
@reza-ebrahimi try this one https://github.com/acplt/open62541/tree/nonce please, otherwise we will need to read spec and watch wireshark logs for working clients

**Comment by Stasik0** [comment]
@reza-ebrahimi did it work out?

**Comment by reza-ebrahimi** [comment]
@Stasik0 There is a problem, How can I generate two header and source (open62541.h and open62541.c) single files? I used two single files in my project not repository project, Please tell me and I'll test it by today.

**Comment by FlorianPalm** [comment]
You have to change the CMake configuration -> activate ENABLE_AMALGAMATION

**Comment by reza-ebrahimi** [comment]
@FlorianPalm Thanks a lot...

**Comment by reza-ebrahimi** [comment]
@Stasik0 Still I get ```UA_STATUSCODE_BADNONCEINVALID``` in ```UA_Client_connect()``` function with https://ci.appveyor.com/project/Stasik0/open62541/build/560/artifacts single header and source files.

**Comment by Stasik0** [comment]
Is there a demo version of the wrapper i can debug?

**Comment by reza-ebrahimi** [comment]
MatrikonOPC Wrapper could be downloaded from here https://www.matrikonopc.com/opc-ua/products/ua-wrapper-com-opc-servers.aspx
unfortunately that was an executable file and should be installed on system, after that wrapper wraps OPC DA servers installed on system and give you a Opc Ua server address, simply I have changed the address path in ```UA_Client_connect()``` function.

**Comment by Stasik0** [comment]
which OPC DA server are you using?

**Comment by reza-ebrahimi** [comment]
Matrikon OPC Server for Simulation

**Comment by Stasik0** [comment]
okay, without tested it yet, could you try that one http://open62541.org/releases/94c0250da6.zip

**Comment by reza-ebrahimi** [comment]
Wow, That's great, ```UA_Client_connect()``` returns ```UA_STATUSCODE_GOOD```,
Thank you, but what happens?

**Comment by Stasik0** [comment]
i have set nonce to be complete empty, it seems that is required by the server (and probably this is standard-conform way to do it). I will reintegrate fix into the master.

**Comment by Stasik0** [comment]
@reza-ebrahimi i reopened it, will have to test tommorow

**Comment by reza-ebrahimi** [comment]
@Stasik0 Ook, Thank you, can I have your email address?

**Comment by Stasik0** [comment]
if i post it here - a spam wave will arrive here, have a look into the chat: http://webchat.freenode.net/?channels=%23open62541
