### ISSUE TITLE
UA_DataSource release callback dissapeared

### ISSUE THREAD

**Issue by osaiz** [acplt/open62541#432]
In trunk versión the .release callback has dissapeared from UA_DataSource.

So I wonder:
-Where should I make the release of the memory allocated in .read callbacks?
 
For instance, in the server example, in the readTemperature callback, this memory allocation is done:
	UA_Double* currentTemperature = UA_Double_new();
And the reléase is done in  releaseTemperature callback
     static void releaseTemperature(void *handle, UA_DataValue *value) {
         if(value->hasValue)
             UA_Double_delete((UA_Double*)value->value.data);
     }

In last version the reléase callback does not exist any more.
So, where should I free the memory allocated by UA_Double_new()  ?

**Comment by jpfr** [comment]
See the API documentation in the header:
https://github.com/acplt/open62541/blob/master/include/ua_server.h#L91

And the example code for datasources:
https://github.com/acplt/open62541/blob/master/examples/server_datasource.c#L26

Just make a copy of the value. It will be deleted internally.
