### ISSUE TITLE
"The message was not entirely processed" in demo server.

### ISSUE THREAD

**Issue by tpiat** [acplt/open62541#443]
Every 40 s: info/communication        The message was not entirely processed, skipping to the end
I have use only UA_Client_read.
No subscriptions.

What could it be?

**Comment by jpfr** [comment]
Hey @tpiat,
probably the client tries to create a subscriptions.
Our server will not recognize the request (since subscriptions are disabled) and discard it.
That's perfectly normal.

**Comment by tpiat** [comment]
I wrote this client. Subscriptions generated automatically wihtout my participation?

**Comment by jpfr** [comment]
Ok. Then we shall look into it.
- Can you trace what service you call when the error happens?
- Is the 40s interval regular?
- Maybe provide a dump of the network stream with `tcpdump` or wireshark.

**Comment by tpiat** [comment]
```
[10/16/2015 12:14:20.509.000]
[10/16/2015 12:15:00.552.000]
[10/16/2015 12:15:40.595.000]
[10/16/2015 12:16:20.639.000]
[10/16/2015 12:17:00.683.000]
[10/16/2015 12:17:40.726.000]
[10/16/2015 12:18:20.769.000]
```
I don't understand how trace it.
Now I'm trying made dump, but server and client on the same computer. I have started demo server on linux but no similar messages.
I will try to get a dump from one computer

**Comment by tpiat** [comment]
Probably I know, why...
There are another opc software on my computer. Including SIMATIC. It can send dubscriptions.

Thanks!!!
