### ISSUE TITLE
Subscriptions don't work on most ServerStatus variables

### ISSUE THREAD

**Issue by jpfr** [acplt/open62541#451]
Of all the variables contained in `/Objects/ServerStatus`, only `CurrentTime` can be subscribed with UA Expert.

**Comment by ichrispa** [comment]
Do the datavalues in serverobject change? Do they maintain their node ID when they change?

Subscriptions work on just about any DataValue. They currently dont support modelchanges and event changes.

**Comment by jpfr** [comment]
Only CurrentTime changes, the rest are constant.
Maybe we fail to send out the original value. So UA Expert never gets something to show.
