### ISSUE TITLE
449 bis: SIFSEGV

### ISSUE THREAD

**Issue by tpiat** [acplt/open62541#453]
I have downloaded last verison open62541m and received SIGSEGV in line

LIST_FOREACH_SAFE(cp, &session->continuationPoints, pointers, temp) 
function UA_Session_deleteMembersCleanup

**Comment by Stasik0** [comment]
and the code? which server are you running?

**Comment by tpiat** [comment]
Client and server writed by me. Codes placed in #449.
--
Отправлено из Mail.Ru для Android пятница, 23 октября 2015г., 09:59 +03:00 от Sten Grüner < notifications@github.com> :

**Comment by Stasik0** [comment]
how to reproduce? 

1) does server crashes on ctrl-c?
2) does client need to be invoked?
....

**Comment by tpiat** [comment]
Server works abour minute. Then appears sigsegv.
--
Отправлено из Mail.Ru для Android пятница, 23 октября 2015г., 10:07 +03:00 от Sten Grüner < notifications@github.com> :

**Comment by tpiat** [comment]
Client must be running.

**Comment by Stasik0** [comment]
is it happening during the periodic cleanup? Can you show the whole stack?

**Comment by tpiat** [comment]
I wrote stack in #449.  
Client disconnect and after reconnecting server crashes.  пятница, 23 октября 2015г., 10:21 +03:00 от Sten Grüner < notifications@github.com> :

**Comment by Stasik0** [comment]
hi, can you try the newest commit? its is not directly the cp pointer, but another bug during cleanup

**Comment by tpiat** [comment]
Without DBG it works (or do not crashed). Tomorrow I'll test it with DBG.

**Comment by tpiat** [comment]
46c6388cb3
Tested. Close.
