### ISSUE TITLE
Reauth coveralls integration

### ISSUE THREAD

**Issue by jpfr** [acplt/open62541#463]
Checking individual files on coveralls gives
> The owner of this repo needs to re-authorize with github; their OAuth credentials are no longer valid so the file cannot be pulled from the github API.

It would be could to see on the file levels, where we don't have coverage.
Who is / can act as the owner of the repo?

**Comment by HolgerJeromin** [comment]
I have reauthenticated something for coveralls. Is this valid only for me, or also for you?
