### ISSUE TITLE
Temperature for embedded linux other than Rpi in examples\server.c

### ISSUE THREAD

**Issue by fchaxel** [acplt/open62541#470]
Two comments could be added for fast modification of the temperature file for Beaglebone and Edison. Same behaviour, divide by ten must also be done.
... or maybe the 3 open tests.

server.c line 243

	// Change to /sys/class/hwmon/hwmon0/device/temp1_input for Beaglebone
	// Change to /sys/class/thermal/thermal_zone3/temp ou /sys/class/thermal/thermal_zone4/temp for Intel Edison

**Comment by HolgerJeromin** [comment]
Can you prepare a pull request? That way you will be on the list of contributors of this repository. :-)

**Comment by jpfr** [comment]
Just pushed the change.
Thank you @fchaxel.
