### ISSUE TITLE
UA_String problem

### ISSUE THREAD

**Issue by tpiat** [acplt/open62541#477]
In version 23980d297d Client works.
After updating to 2f4a056607 UA_String do not works, string has length equials 0xababab00.
What changes has been made in this part?
d4bf5e03ce does not works too.

**Comment by Stasik0** [comment]
The string length has changed from signed to unsigned, could you please show your code - you will probably will need to update it

**Comment by tpiat** [comment]
What I must change?

**Comment by Stasik0** [comment]
well, the main change is this one: https://github.com/acplt/open62541/blob/06b6687b3f25dc01ee31b0d1fa1c4e87dedaccd2/include/ua_types.h#L95

from UA_Int32 -> size_t

**Comment by tpiat** [comment]
I don't use type of length.
And array of string works but scalar -- do not works.

**Comment by Stasik0** [comment]
well, we need to see some code, otherway try to compare your code to the current examples that we have https://github.com/acplt/open62541/tree/master/examples

**Comment by tpiat** [comment]
Thanks!
Error in length of data.

int arrayLenl = rResp.results[i].value.arrayLength;
array lenght was -1 but now it equals 0 in scalar value.
