### ISSUE TITLE
xml2ns: add the rest of the possible nodes belo UA_NodeSet to the UA_NodeSet 

### ISSUE THREAD

**Issue by uleon** [acplt/open62541#61]

**Comment by ichrispa** [comment]
The item is currently being worked on by me as a delegated request from uleon.

My thesis produced a somewhat big script that creates a python based class representation for the node contents of any XML-based namespace. I am modifying the code to create nodes based on the namespace init model hard-coded in src/server/ua_server.c:UA_Server_new(void).
