### ISSUE TITLE
Read structure types in ns0

### ISSUE THREAD

**Issue by jpfr** [acplt/open62541#73]
Namespace 0 contains structures, such as the ServerStatus object.

```xml
  <UAVariable NodeId="i=2256" BrowseName="ServerStatus" ParentNodeId="i=2253" DataType="i=862" MinimumSamplingInterval="1000">
    <DisplayName>ServerStatus</DisplayName>
    <Description>The current status of the server.</Description>
    <References>
      <Reference ReferenceType="HasComponent">i=2257</Reference>
      <Reference ReferenceType="HasComponent">i=2258</Reference>
      <Reference ReferenceType="HasComponent">i=2259</Reference>
      <Reference ReferenceType="HasComponent">i=2260</Reference>
      <Reference ReferenceType="HasComponent">i=2992</Reference>
      <Reference ReferenceType="HasComponent">i=2993</Reference>
      <Reference ReferenceType="HasTypeDefinition">i=2138</Reference>
      <Reference ReferenceType="HasComponent" IsForward="false">i=2253</Reference>
    </References>
  </UAVariable>
```

Internally, we have a struct to represent the ServerStatus.
```c
typedef struct UA_ServerStatusDataType {
	UA_DateTime startTime;
	UA_DateTime currentTime;
	UA_ServerState state;
	UA_BuildInfo buildInfo;
	UA_UInt32 secondsTillShutdown;
	UA_LocalizedText shutdownReason;
} UA_ServerStatusDataType;
```

But, the read service would need to "find" all the components in the namespace and piece them together via the hasComponent reference. It seems, there is no actual "UA_ServerStatusDataType" stored in the node as a variant.

Or we could have the "component" UA_Node->values point to members of the "master" UA_ServerStatusDataType. But that makes freeing problematic..

If we just operate dynamically on the VariableTypeNode, do we need the ```UA_ServerStatusDataType``` then?

**Comment by Stasik0** [comment]
this one can be closed since the pyhton script by @ichrispa is there, right?

**Comment by ichrispa** [comment]
@Stasik0: I agree. this issue is a bit antiquated.
