### ISSUE TITLE
merging of xml2ns0.c into appMockup_init() to get a working prototype

### ISSUE THREAD

**Issue by Stasik0** [acplt/open62541#85]
Hi @uleon,

me and @FlorianPalm just reviewed the tons of work you have done in parsing xml stuff - great work. As far as we could see the generateSam seems not to be quite finished atm while connecting the data with the variableNodes.

Would it help if we start merging just the namespace generation into appMockup_init() with an option to fill in the data manually (looking forward the presentation at automation14)? Or should we wait/contribute to generateSam.c? I can start with getting an encode_base64 function from somewhere.

**Comment by jpfr** [comment]
closing the issue.
we can resurrect it when xml encoding becomes relevant again.
